### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by scourii**
Hi, I tried to improve some of the formatting on the code and simplify it with a bit of spare time I had, I will potentially add a bit more later. Unfortunately the project doesn't work on my end because I'm not using WIndows, but I think these modifications should help. If you're able to check that would be great!

### CODE REVIEW

**Comment by anahibemol** [comment]
Thanks <3 You do not understand how much I needed that help, I never got able to figure out how to format a project into multiple files and you not only did that but also got to improve it.

You are priceless, i'll merge it.

**Comment by scourii** [comment]
Glad it still managed to work, no problem man! I left a few comments in the code for other things that I couldn't get to, if you have time for them.

**Comment by anahibemol** [comment]
> Glad it still managed to work, no problem man! I left a few comments in the code for other things that I couldn't get to, if you have time for them.

I'll try to get into it later, do you mind if I credit you in some way on the code, I'd really like to.

**Comment by scourii** [comment]
All up to you, I don't mind regardless

**Pull request merged**
